---
- hosts: webserver
  become: true
  become_user: root
  tasks:
  - name: install multiple packages on ansible host
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
